services:
  backend:
    build:
      context: ./backend
    container_name: app_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - UID=1000
      - GID=1000
    expose:
      - "5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    container_name: app_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
