services:
  backend:
    build:
      context: ./backend
    container_name: app_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
    container_name: app_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
